basePath: /users
definitions:
  model.User:
    properties:
      email:
        type: string
      name:
        type: string
    type: object
host: localhost:1323
info:
  contact:
    email: nik3348@gmail.com
    name: API Support
    url: https://voidstack.xyz
  description: This is a sample Backend CRUD App using Golang.
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: GoMe
  version: "1.0"
paths:
  /admin/auth:
    post:
      consumes:
      - application/json
      description: get admin info
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      security:
      - ApiKeyAuth: []
      summary: Auth admin
      tags:
      - accounts
      - admin
swagger: "2.0"
